<a href="https://colab.research.google.com/github/jerom19/numpy-task/blob/main/Numpy_tasks1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [15]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [4]:
print(np.__version__)
print(np.show_config)

1.21.6
<function show at 0x7f362a6f3290>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [5]:
s=np.zeros(10)
s

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [6]:
print(s.size)
print(s.itemsize)

10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [8]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
s[4]=1
s

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
x=x[::-1]
x

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
c=np.arange(0,9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
non_zero=np.nonzero([1,2,0,0,4,0])
non_zero


(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
i_d=np.eye(3,3)
i_d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
random_values=np.random.random((3,3,3))
random_values

array([[[0.23889566, 0.33376929, 0.04352808],
        [0.271128  , 0.72359714, 0.80157337],
        [0.22408759, 0.1665715 , 0.08139088]],

       [[0.49237453, 0.60617125, 0.03567088],
        [0.47777748, 0.91562982, 0.74922914],
        [0.00872218, 0.43101956, 0.28631563]],

       [[0.41455337, 0.4289594 , 0.92922543],
        [0.5315118 , 0.06582128, 0.93428604],
        [0.73374101, 0.85144855, 0.94007558]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
random_values=np.random.random((10,10))
xmin,xmax=random_values.min(),random_values.max()
print(xmin,xmax)


0.02321011559544639 0.9959725117202056


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
s=np.random.random(30)
c=s.mean()
c

0.5027499477208558

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
s=np.ones((5,5))
s[1:-1,1:-1]=0
s

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
d=np.pad(s,1)
d

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
s=np.diag(1+np.arange(4),k=-1)
s

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
s=np.zeros((8,8))
s[1::2,::2]=1
s[::2,1::2]=1
s

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
c=np.unravel_index(100,(6,7,8))
c

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
s=np.array(([1,0],[1,0]))
c=np.tile(s,(4,4))
c

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
s=np.random.random((5,5))
xmax,xmin=s.max(),s.min()
s=(s-xmin)/(xmax-xmin)
print(s)

[[0.81942921 0.02421003 0.41630757 0.29194863 1.        ]
 [0.46441008 0.59566095 0.89618818 0.38834344 0.14106774]
 [0.5445746  0.         0.32954053 0.14000414 0.42649721]
 [0.03354062 0.271122   0.84124474 0.39718726 0.3603111 ]
 [0.14352088 0.77413129 0.58475022 0.58788792 0.45796796]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color=np.dtype([('R',np.ubyte,1),('G',np.ubyte,1),('B',np.ubyte,1),('A',np.ubyte,1)])
print(color)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [9]:
x = np.arange(15).reshape((5, 3))
y = np.arange(6).reshape((3, 2))
np.dot(x,y)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x = np.arange(10)
x[(x >= 3) & (x <= 8)] = -1
print(x)


[ 0  1  2 -1 -1 -1 -1 -1 -1  9]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)


```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [11]:
Z=np.arange(3)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)

[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x = np.random.uniform(12,50)
c=np.copysign(np.ceil(np.abs(x)), x)
print(c)

16.0


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x = np.arange(0, 10)
y = np.arange(5, 15)
np.intersect1d(x, y)

array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
Z

array([inf])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
yesterday
today
tomorrow

numpy.datetime64('2022-10-23')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))


[7. 5. 1. 4. 8. 0. 4. 8. 4. 2.]
[7. 5. 1. 4. 8. 0. 4. 8. 4. 2.]
[7. 5. 1. 4. 8. 0. 4. 8. 4. 2.]
[7 5 1 4 8 0 4 8 4 2]
[7. 5. 1. 4. 8. 0. 4. 8. 4. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.0984156  0.24827308 0.32784886 0.34655144 0.41243893 0.4640648
 0.57753929 0.74437011 0.9672985  0.97159852]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [14]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.92878232 1.1249297  0.82049747 0.48841918 0.9634673  0.90969729
 0.97702863 0.39961588 1.07336299 1.02576371]
[0.07160565 0.91788376 1.36318034 0.67730594 1.50846487 0.39347875
 0.61860409 1.36017019 1.04745977 0.39394632]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.00178709 0.57313367 0.31943993 0.         0.265106   0.23102279
 0.53003661 0.14983267 0.95620704 0.93661221]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
h=np.set_printoptions(threshold=10)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

75


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),('color',    [ ('r', float, 1),('g', float, 1),('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
import scipy
import scipy.spatial
Z = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
Z = np.random.random((100,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.90828697 0.89959978 ... 0.12500447 0.39188765 0.60510861]
 [0.90828697 0.         0.36702865 ... 0.93478164 0.53747657 0.33346287]
 [0.89959978 0.36702865 0.         ... 0.87558565 0.51632083 0.33652529]
 ...
 [0.12500447 0.93478164 0.87558565 ... 0.         0.3988223  0.61286974]
 [0.39188765 0.53747657 0.51632083 ... 0.3988223  0.         0.21540856]
 [0.60510861 0.33346287 0.33652529 ... 0.61286974 0.21540856 0.        ]]
[[0.         0.80473242 0.70196673 ... 0.53661457 0.18370833 0.10792047]
 [0.80473242 0.         0.24448376 ... 0.39377822 0.92402059 0.72299393]
 [0.70196673 0.24448376 0.         ... 0.47298615 0.78054111 0.64641281]
 ...
 [0.53661457 0.39377822 0.47298615 ... 0.         0.70299721 0.43205701]
 [0.18370833 0.92402059 0.78054111 ... 0.70299721 0.         0.288941  ]
 [0.10792047 0.72299393 0.64641281 ... 0.43205701 0.288941   0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s =StringIO ("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 ...
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[ 0.26630185 -0.47947373 -0.3407958  ...  0.19679301  0.07610473
   0.11032208]
 [-0.1130559   0.26669252 -0.49943336 ...  0.09073143 -0.14420821
  -0.26951569]
 [-0.20641931  0.11388213  0.07525657 ...  0.2244334  -0.18694583
  -0.26982171]
 [-0.28886715 -0.40342596 -0.29763438 ...  0.00176917 -0.15352135
   0.25668747]
 [-0.263247    0.18428127  0.24132487 ... -0.21417591  0.42242073
  -0.01220622]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:1].argsort()])

[[0 6 6]
 [8 9 0]
 [0 8 8]]
[[[0 6 6]
  [8 9 0]
  [0 8 8]]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.46597539657273634


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
Z = np.ones(10)

I = np.random.randint(0,len(Z),20)

Z += np.bincount(I, minlength=len(Z))

print(Z)

[3. 1. 5. 5. 2. 2. 4. 4. 2. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6]

I = [1,3,9,3,4,1]

F = np.bincount(I,X)

print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w,h = 16,16

I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)

F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]

n = len(np.unique(F))

print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[60 46 59 46]
 [58 52 84 60]
 [48 60 51 49]]
[[60 46 59 46]
 [58 52 84 60]
 [48 60 51 49]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D = np.random.uniform(0,1,100)

S = np.random.randint(0,10,100)

D_sums = np.bincount(S, weights=D)

D_counts = np.bincount(S)

D_means = D_sums / D_counts

print(D_means)

[0.59325862 0.46234984 0.25491581 0.41993881 0.5248555  0.51236324
 0.60521723 0.56858682 0.57820834 0.57027457]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))
np.sum(A * B.T, axis=1)
np.einsum("ij,ji->i", A, B)

array([1.62016632, 0.33481031, 1.11332797, 0.59112429, 1.69928581])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
Z = np.array([1,2,3,4,5])

nz = 3

Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))

Z0[::nz+1] = Z

print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
A = np.ones((5,5,3))

B = 2*np.ones((5,5))

print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
A = np.arange(25).reshape(5,5)

A[[0,1]] = A[[1,0]]

print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 10) ( 0, 78) ( 2, 60) ( 2, 97) ( 7, 28) ( 7, 30) ( 7, 95) ( 7, 99)
 (10, 78) (14, 32) (14, 56) (28, 30) (29, 55) (29, 86) (32, 56) (34, 49)
 (34, 77) (37, 37) (37, 82) (40, 40) (40, 89) (49, 77) (52, 73) (52, 94)
 (55, 86) (60, 97) (73, 94) (95, 99)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])

A = np.repeat(np.arange(len(C)), C)

print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a, n=3) :

      ret = np.cumsum(a, dtype=float)

      ret[n:] = ret[n:] - ret[:-n]

      return ret[n - 1:] / n

      Z = np.arange(20)

print(moving_average(Z, n=3))

[2. 3. 4.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks
def rolling(a, window):
  shape = (a.size - window + 1, window)
  strides = (a.itemsize, a.itemsize)
  return stride_tricks.as_strided(a, shape=shape, strides=strides)
  Z = rolling(np.arange(10), 3)
print(Z)

[1 2 3 4 5]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
Z = np.random.randint(0,2,100)

np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)

np.negative(Z, out=Z)

array([-0.78501772, -0.57800222,  0.58571238,  0.83325072, -0.17906915,
        0.43040209,  0.20906578,  0.59183537,  0.58003695,  0.75714957,
       -0.10419477,  0.04613861, -0.49883521, -0.86955382, -0.42427195,
        0.10550849,  0.07769367, -0.73013748,  0.60977129,  0.61573074,
        0.42294178,  0.13561194,  0.25862456,  0.69042282, -0.71413655,
        0.62120085, -0.85007037,  0.90888433,  0.70314584,  0.04312959,
        0.20423834,  0.59747391,  0.83695059,  0.02189325, -0.64422041,
       -0.90552583,  0.15628372,  0.37691934, -0.93922227, -0.62449391,
        0.12024416, -0.63459317,  0.24867343, -0.41368113, -0.43911027,
        0.6490991 ,  0.75545657, -0.04320039, -0.31639091, -0.53753097,
       -0.21829464,  0.0858796 , -0.14744325, -0.50826456, -0.03094098,
       -0.38470372,  0.77212875, -0.55079286, -0.86550056,  0.50712257,
        0.27042586,  0.09039899,  0.6091415 , -0.97936317, -0.34835194,
       -0.8036492 ,  0.26536879, -0.64860854, -0.66806473,  0.52

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
  T = P1 - P0
  L = (T**2).sum(axis=1)
  U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
  U = U.reshape(len(U),1)
  D = P0 + U*T - p
  return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[1.44612711e+00 3.93181079e+00 5.60861954e+00 4.32342385e+00
 4.02130641e-01 2.69173086e+00 3.24450184e+00 3.83483537e+00
 2.35596727e-03 2.05653444e+00]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))

P1 = np.random.uniform(-10,10,(10,2))

p = np.random.uniform(-10, 10, (10,2))

print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 5.22133294 10.05252792 10.75693217  3.21665821 13.60852467  8.76856819
   8.08957689  3.99989111 11.4986836   6.36513025]
 [ 4.86871157  0.42237491  1.4694469   6.60834667  6.92468797  0.34156246
  12.55803041  2.36565164  9.00239201  0.41790108]
 [ 2.92799794  3.7451484   3.08249039  5.12515405  0.82895063 15.89009537
   5.078227   11.60565799  3.97621634 17.9048243 ]
 [ 7.02656338 11.77363601 12.41608655  4.9763224  14.79930676 10.28030315
   7.28377254  4.28546204 11.93863212  7.43492746]
 [ 3.25567962  4.11732087  3.46438332  5.38447014  1.20848776 16.03337725
   5.01869336 11.33277476  3.68004952 17.91195707]
 [ 1.64616476  4.43558736  5.70214381  4.41323317 11.62266973  0.97582969
  14.35959356  6.35546169 13.19318059  0.61726274]
 [ 0.90810854  5.17170192  6.42431408  3.72643896 12.19823641  1.52268863
  14.14190042  6.59224851 13.49051041  0.28145791]
 [ 6.7483208   8.42403988  7.99394697  7.8066609   6.1830533  16.81483992
   3.21372254  7.16708452  0.70686237 16.92417634]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[1 1 5 2 7 8 9 0 2 9]
 [3 4 1 3 6 8 3 2 5 0]
 [4 1 5 0 6 9 2 4 9 8]
 [7 2 2 4 0 7 8 3 0 7]
 [1 1 8 5 8 7 6 6 7 5]
 [3 2 8 1 1 3 6 3 6 7]
 [2 8 9 3 0 3 9 9 4 2]
 [0 7 7 2 2 8 0 3 4 3]
 [8 4 6 6 8 6 4 6 2 6]
 [2 0 7 3 5 0 2 9 3 2]]
[[0 0 0 0 0]
 [0 1 1 5 2]
 [0 3 4 1 3]
 [0 4 1 5 0]
 [0 7 2 2 4]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)

R = stride_tricks.as_strided(Z,(11,4),(4,4))

print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
Z = np.random.randint(0,10,50)

print(np.bincount(Z).argmax())

9


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 3 0]
   [4 0 3]
   [0 4 3]]

  [[3 0 3]
   [0 3 2]
   [4 3 4]]

  [[0 3 1]
   [3 2 4]
   [3 4 4]]

  [[3 1 1]
   [2 4 3]
   [4 4 1]]

  [[1 1 2]
   [4 3 3]
   [4 1 3]]

  [[1 2 2]
   [3 3 1]
   [1 3 4]]

  [[2 2 3]
   [3 1 0]
   [3 4 3]]

  [[2 3 3]
   [1 0 4]
   [4 3 1]]]


 [[[4 0 3]
   [0 4 3]
   [0 3 1]]

  [[0 3 2]
   [4 3 4]
   [3 1 1]]

  [[3 2 4]
   [3 4 4]
   [1 1 4]]

  [[2 4 3]
   [4 4 1]
   [1 4 3]]

  [[4 3 3]
   [4 1 3]
   [4 3 2]]

  [[3 3 1]
   [1 3 4]
   [3 2 1]]

  [[3 1 0]
   [3 4 3]
   [2 1 0]]

  [[1 0 4]
   [4 3 1]
   [1 0 0]]]


 [[[0 4 3]
   [0 3 1]
   [1 3 3]]

  [[4 3 4]
   [3 1 1]
   [3 3 4]]

  [[3 4 4]
   [1 1 4]
   [3 4 4]]

  [[4 4 1]
   [1 4 3]
   [4 4 1]]

  [[4 1 3]
   [4 3 2]
   [4 1 0]]

  [[1 3 4]
   [3 2 1]
   [1 0 3]]

  [[3 4 3]
   [2 1 0]
   [0 3 2]]

  [[4 3 1]
   [1 0 0]
   [3 2 2]]]


 [[[0 3 1]
   [1 3 3]
   [4 2 2]]

  [[3 1 1]
   [3 3 4]
   [2 2 1]]

  [[1 1 4]
   [3 4 4]
   [2 1 3]]

  [[1 4 3]
   [4 4 1]
   [1 3 3]]

  [[4 3 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):

  def __setitem__(self, index, value):

    i,j = index

    super(Symetric, self).__setitem__((i,j), value)

    super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):

  return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  8  9  7  4]
 [ 8  0 12  9  9]
 [ 9 12  2 42 16]
 [ 7  9 42  2 10]
 [ 4  9 16 10  7]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20

M = np.ones((p,n,n))

V = np.ones((p,n,1))

S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])

print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z = np.ones((16,16))

k = 4

S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),

np.arange(0, Z.shape[1], k), axis=1)

print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):


  N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +

      Z[1:-1,0:-2] + Z[1:-1,2:] +

      Z[2: ,0:-2] + Z[2: ,1:-1] + Z[2: ,2:])

  birth = (N==3) & (Z[1:-1,1:-1]==0)

  survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)

  Z[...] = 0

  Z[1:-1,1:-1][birth | survive] = 1

  return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): 
  Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9996 9999 9997 9998 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.52 s ± 65 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
208 ms ± 7.59 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
172 ms ± 8.07 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))

B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)

rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]

print(rows)

[0 1 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))

E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)

U = Z[~E]

print(Z)

print(U)

[[0 0 3]
 [3 0 4]
 [4 3 3]
 [1 2 1]
 [4 1 3]
 [4 1 3]
 [2 2 3]
 [3 0 4]
 [2 3 4]
 [3 4 4]]
[[0 0 3]
 [3 0 4]
 [4 3 3]
 [1 2 1]
 [4 1 3]
 [4 1 3]
 [2 2 3]
 [3 0 4]
 [2 3 4]
 [3 4 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_,idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[[0 0 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)      
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)   
np.einsum('i,j->ij', A, B)

array([[3.06752191e-01, 4.08077852e-01, 1.61090539e-01, 2.52372997e-01,
        2.23484887e-01, 3.59052762e-01, 2.92955726e-01, 5.64309109e-02,
        7.37469339e-01, 5.21308080e-01],
       [1.33569794e-01, 1.77690254e-01, 7.01440143e-02, 1.09891340e-01,
        9.73125252e-02, 1.56343149e-01, 1.27562368e-01, 2.45718380e-02,
        3.21117927e-01, 2.26994346e-01],
       [2.11037357e-01, 2.80746720e-01, 1.10826011e-01, 1.73625917e-01,
        1.53751664e-01, 2.47018760e-01, 2.01545756e-01, 3.88229674e-02,
        5.07359312e-01, 3.58646109e-01],
       [3.43698928e-04, 4.57228748e-04, 1.80493073e-04, 2.82770038e-04,
        2.50402502e-04, 4.02298836e-04, 3.28240749e-04, 6.32277263e-05,
        8.26293761e-04, 5.84096980e-04],
       [8.24158320e-02, 1.09639235e-01, 4.32805736e-02, 6.78056462e-02,
        6.00442097e-02, 9.64675493e-02, 7.87091033e-02, 1.51614254e-02,
        1.98137620e-01, 1.40061067e-01],
       [2.25031737e-01, 2.99363690e-01, 1.18175142e-01, 1.85139456e-01,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)      
y_int = np.interp(r_int, r, y)


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100)

N = 1000 

idx = np.random.randint(0, X.size, (N, X.size))

means = X[idx].mean(axis=1)

confint = np.percentile(means, [2.5, 97.5])

print(confint)

[-0.15707853  0.20532536]
